package harusame.core.util;

/**
 *
 * @author Hikari
 */
public enum TileType {
    STONEWALL_UPPER_LEFT, STONEWALL_UPPER_MIDDLE, STONEWALL_UPPER_RIGHT, 
    STONEWALL_LEFT, STONEWALL_RIGHT,
    STONEWALL_BOTTOM_LEFT, STONEWALL_BOTTOM_MIDDLE, STONEWALL_BOTTOM_RIGHT
}  
